package br.com.brunoxkk0.sp.mod.core;

import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import net.minecraftforge.fml.common.DummyModContainer;
import net.minecraftforge.fml.common.LoadController;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;


public class SyrxModContainer extends DummyModContainer {

    private final ModMetadata metadata;
    private Logger logger;

    public SyrxModContainer(String modId, String modName, String modVersion){
        super(new ModMetadata());

        metadata = getMetadata();

        this.metadata.autogenerated = false;
        this.metadata.authorList.add("brunoxkk0");
        this.metadata.credits = "brunoxkk0";
        this.metadata.modId = modId;
        this.metadata.name = modName;
        this.metadata.version = modVersion;
    }

    @Override
    public boolean registerBus(EventBus bus, LoadController controller) {
        bus.register(this);
        return true;
    }

    public Logger getLogger() {
        return LogManager.getLogger(metadata.name);
    }

    @Override
    public String getModId() {
        return metadata.modId;
    }

    @Override
    public String getName() {
        return metadata.name;
    }

    @Override
    public String getVersion() {
        return metadata.version;
    }
}
